### ISSUE TITLE
Search for patches

### ISSUE THREAD

**Issue by ghost** [madscientist42/runit#3]
We should look at and review patches made by other distros initially, as they may be very relevant to the current code base.  Debian has a number of small patches, most are related to build & directory layout, which may get fixed thru cmake, but there is:

0002-support-etc-runit-nosync-file-to-make-sync-on-shutdow.diff
0003-utmpset.c-mixes-int32_t-and-time_t.diff

And a few others that should be looked at there.  There may well be some in gentoo and void to review also.

**Comment by madscientist42** [comment]
Yeah.  I'll get that going here shortly then.  We want to take their stuff where it makes sense as commits to our upstream.  It should be meshed in before I do the CMake mods or we'll have no end to "fun" trying to get them all integrated in.

**Comment by ghost** [comment]
Yep, we should get patches in as commits that make sense while it is all still cleanly patchable.  I only looked at debian so far, but I am sure other distros may have similar patches to review.

**Comment by madscientist42** [comment]
Base critical Debian patches in on the cmake-rework branch.  Gentoo appears to adopt the same base fixes Debian does (and refers to them in the appropriate .ebuild file).  Looking at Void.  I think we're almost good enough right now to re-work this because much of the patches are "correcting" misbehaviors regarding the packaging process, directory structures for scripting, and the actual init system config and scripting itself- which should be considered a separate affair from the toolset and a basic system init framework to build upon...

**Comment by madscientist42** [comment]
Looks like Void applies the one patch from Debian where int32_t is passed in for time_t in the original and Debian correctly un-does that sin.

They also fix the build system to do cross-compilation since Void expects to do that as part of their build process.

So...all the main crucial patches are now in.  Will move to re-structure for CMake purposes.

**Comment by ghost** [comment]
@madscientist42  I think the initial cmake you have is nice, simple, and straightforward...

**Comment by madscientist42** [comment]
As simple as is needed is best.  :D

**Comment by madscientist42** [comment]
Initial patchwork finished.  Closing
